"""add room_code and is_public to battles

Revision ID: e2d3d88fe660
Revises: 7701224ad951
Create Date: 2025-06-28 10:23:35.528644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d3d88fe660'
down_revision: Union[str, None] = '7701224ad951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('room_code', sa.String(length=6), nullable=True))
    op.add_column('battles', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.alter_column('battles', 'opponent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'battles', ['room_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battles', type_='unique')
    op.alter_column('battles', 'opponent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('battles', 'is_public')
    op.drop_column('battles', 'room_code')
    # ### end Alembic commands ###
